Iter13
ulixes-bloom/ya-metrics pull request #13
Opened 2024-11-11 08:34 UTC by ulixes-bloom

2024-11-13 22:22 UTC, bulbetski requested changes
Слушай, код хороший, видно, что стараешься.
В основном замечания по обработке ошибок. Так же варианта рефакторинга обсудили на 1-1 встрече.

2024-11-13 22:22 UTC, bulbetski commented on internal/agent/client/client.go
> +		log.Fatalf("impossible to marshall metrics: %s", err)
Ошибка сериализации выводится через `log.Fatalf`, что завершает выполнение программы в случае ошибки. Здесь лучше вернеть ошибку и залогировать её в месте вызова. Вообще log.Fatal нигде кроме main функций быть не должно (если еще где-то есть, исправь, не буду коммент дублировать)

2024-11-13 22:22 UTC, bulbetski commented on internal/agent/client/client.go
>  		return
Здесь мы никак не обрабатываем ошибку. Надо хотя бы залогировать. 

Ниже у нас идёт client.Do(), там та же песня. Также не стоит забывать, что err в случае client.Do() это ошибка, возникающая при непосредственной отправке запросе, а ошибка, возникшая в ходе обработки запроса. То есть какой-нибудь InternalServerError, NotFound и так далее мы не обработаем. После проверки на ошибку так же надо проверять статусный код.

2024-11-13 22:22 UTC, bulbetski commented on internal/pkg/metricerrors/metricerrors.go
> +package metricerrors
да в целом было норм название и до переименования, можно общий пакет errors сделать с разными константами и кастомными типами ошибок -- это ок

2024-11-13 22:22 UTC, bulbetski commented on internal/pkg/retry/retry.go
> +	}
Лог с номерами ошибок создается, но не проверяется, что `e` не содержит пустых ошибок. Рекомендуется добавить проверку для каждого `l != nil`.

2024-11-13 22:22 UTC, bulbetski commented on internal/pkg/retry/retry.go
> +	for shouldRetry && curAttempt != attempts {
Здесь shouldRetry всегда true

2024-11-13 22:22 UTC, bulbetski commented on internal/pkg/retry/retry.go
> +func nextAttemptTimeout(prevT *time.Duration) *time.Duration {
лучше возвращать значение, чтобы не разыменовывать указатель лишний раз

2024-11-13 22:22 UTC, bulbetski commented on internal/server/api/api.go
>  	}
лучше инициализировать лог в мэйне и там фаталиться, если хочешь инициализировать логер тут, то надо возвращать ошибку в мэйн и опять же фаталиться там

2024-11-13 22:22 UTC, bulbetski commented on internal/server/api/api.go
> +		storage = memory.NewStorage(logger, conf)
Оба хранилища лучше инициализировать в мэйне и там же фаталится, сюда можно прокинуть уже интерфейсы и не парится по поводу того, инициализированы они или нет

2024-11-13 22:22 UTC, bulbetski commented on internal/server/api/api.go
>  	newAPI.router = newAPI.newRouter()
В случае с роутером стоит вообще сделать отдельный пакет, но это больше рекомендация

2024-11-13 22:22 UTC, bulbetski commented on internal/server/service/service.go
> +	storage.Setup()
не обработали ошибку

2024-11-13 22:22 UTC, bulbetski commented on internal/server/service/service.go
> +			metricsMap[m.ID] = strconv.FormatFloat(*m.Value, 'f', -1, 64)
Разыменовываем указатель. Delta и Value могут быть nil. Надо всегда проверять перед такими действиями указатель на nil. Хорошим решением будет сделать у m два метода
GetDelta и GetValue

Пример:
```
func (m *Metric) GetDelta() int {
      if m.Delta == nil {
           return 0
      }
      
      return *m.Delta
} 
```
p.s. типы мог перепутать, но суть такая

2024-11-13 22:22 UTC, bulbetski commented on internal/server/service/service.go
> +			return []byte(""), metricerrors.ErrMetricNotExists
Давай из твоих методов Get будем возвращать ошибку. Так намного прозрачнее. Тогда в каждом кейсе будем логировать и возвращать уже какой-то внятный ответ. А то по контракту кажется, что ошибки произойти не может

2024-11-13 22:22 UTC, bulbetski commented on internal/server/service/service.go
> +			s.storage.Set(*metrics.NewCounterMetric(mname, val))
1.Не обрабатываем ошибки при storage.Set
2. Разыменовываем указатель, чего можно избежать поменяв либо входной параметр у Set, либо поменяв возвращаемый тип у NewCounterMetric и NewGaugeMetric

2024-11-13 22:22 UTC, bulbetski commented on internal/server/storage/memory/memory.go
>  	}
можно создать хелперы для инициализации метрик, либо сразу хелперы для заполнения мапы

2024-11-13 22:22 UTC, bulbetski commented on internal/server/storage/memory/memory.go
>  			newDelta := (*metric.Delta + *cur.Delta)
разыменовываем указатель, уже писал выше

2024-11-13 22:22 UTC, bulbetski commented on internal/server/storage/memory/memory.go
>  	return metric, ok
если НЕ ок, можно вернуть какую-нибудь not found ошибку

2024-11-13 22:22 UTC, bulbetski commented on internal/server/storage/memory/memory.go
>  		return err
в сообщение об ошибке можно добавить путь до файла, так будет проще отлаживать

2024-11-13 22:22 UTC, bulbetski commented on internal/server/storage/pg/pg.go
> +func NewStorage(dsn string) (*pgstorage, error) {
пусть NewStorage принимает на вход сразу же результат соединение с бд из main'а

2024-11-13 22:22 UTC, bulbetski commented on internal/server/storage/pg/pg.go
> +		return &newStorage, err
тут стоило бы возвращать nil, err

2024-11-13 22:22 UTC, bulbetski commented on internal/server/storage/pg/pg.go
> +	return err
if err != nil {
return err
}

return nil

для чистоты кода

2024-11-13 22:22 UTC, bulbetski commented on internal/server/storage/pg/pg.go
> +		cur, ok := ps.Get(metric.ID)
Может вместо обновления через Get сделать сразу какой-нибудь хитрый set/update?

2024-11-13 22:22 UTC, bulbetski commented on internal/server/storage/pg/pg.go
> +func (ps *pgstorage) SetAll(meticsSlice []metrics.Metric) error {
можно заранее проверить длину metricsSlice, чтобы не делать лишний движений, в случае, если он nil или пустой

2024-11-13 22:22 UTC, bulbetski commented on internal/server/storage/pg/pg.go
> +	}
т.к. скан возвращает ошибку, надо вернуть именно её и metrics.Metric{}

2024-11-13 22:22 UTC, bulbetski commented on internal/server/storage/pg/pg.go
> +		}
Если возникнет ошибка при `Scan`, метод вернет только частичные данные. Если мы рассматриваем вариант возврата всех `allMetrics` или никаких, то нужно вернуть просто ошибку, если хотим возвращать часть (что противоречит названию метода), то здесь нужно залогировать и сделать continue

2024-11-13 22:22 UTC, bulbetski commented on internal/server/storage/pg/queries.go
> +package pg
я бы не делал отдельный файл с запросами, смотреть туда-сюда, че там в коде метода, а че там в запросе в разных файлах не очень удобно.
Рекомендую каждый запрос написать внутри соответствующего метода -- это ок

2024-11-15 15:33 UTC, ulixes-bloom commented on internal/agent/client/client.go
> +		log.Fatalf("impossible to marshall metrics: %s", err)
не знаю, как вернуть ошибку из server/api.Run(), оставила log.fatal. там запускается go рутина, чтобы код не завис на http.ListenAndServe
в других местах убрала

2024-11-15 15:33 UTC, ulixes-bloom commented on internal/pkg/metricerrors/metricerrors.go
> +package metricerrors
у меня в одном месте случился конфликт имен со стандартной библиотекой errors. я подумала, что лучше глобально поменять имя своего кастомного пакета, чем использовать алиасы

2024-11-15 20:05 UTC, ulixes-bloom commented on internal/server/storage/pg/pg.go
> +	return err
уточни, а почему такой код лучше? именно визуально так читается лучше/более однородно или есть какая-то техническая причина?

2024-11-15 20:23 UTC, ulixes-bloom commented on internal/server/storage/pg/pg.go
> +		cur, ok := ps.Get(metric.ID)
да, так намного лучше
не подумала про такое решение

2024-11-15 20:41 UTC, ulixes-bloom commented on internal/server/storage/pg/pg.go
> +		}
ну да, частично возвращать нехорошо, получается непредсказуемый результат
поменяла так, чтобы метод возвращал nil, err, если попалась ошибка при получении метрик

2024-11-15 21:05 UTC, ulixes-bloom commented on internal/server/api/api.go
>  	newAPI.router = newAPI.newRouter()
прям отдельный пакет для роутера? или достаточно файла router.go в папке api?

2024-11-15 21:17 UTC, ulixes-bloom commented on internal/server/service/service.go
> +			s.storage.Set(*metrics.NewCounterMetric(mname, val))
поправила 1 и 2
лучше буду передавать по значению, потому что объекты тут небольшие

2024-11-15 21:19 UTC, ulixes-bloom commented on internal/server/storage/memory/memory.go
>  	return metric, ok
возвращаю metricerrors.ErrMetricNotExists

2024-11-15 21:29 UTC, ulixes-bloom commented on internal/server/storage/pg/pg.go
> +func NewStorage(dsn string) (*pgstorage, error) {
а какие в этом преимущества? я с ходу не вижу. может, достаточно будет добавить проверку соединения в NewStorage() и возвращать ошибку в случае неудачи?
еще вот думаю, если появится новая бд, то main расширится конструкциями switch для разных подключений, что выглядит не очень хорошо

2024-11-15 21:33 UTC, ulixes-bloom commented on internal/server/storage/pg/queries.go
> +package pg
а я думала так лучше, потому что sql не мешается с go
можно я пока оставлю так и понаблюдаю, будет ли мешаться этот файлик? если это костыль, то хочется это прочувствовать 😅

2024-11-15 21:54 UTC, ulixes-bloom commented on internal/agent/client/client.go
>  		return
логирование ошибок добавила выше в месте вызова SendMetrics()
добавила проверку статус кода ответа

2024-11-15 22:02 UTC, ulixes-bloom commented on internal/server/storage/memory/memory.go
>  	}
хмхм.. мне кажется, в хелпер должны уходить небольшие переиспользуемые куски кода. но инициализация inmemory структуры выполняется только здесь
пока не очень хочется уносить это в хелпер

2024-11-17 17:09 UTC, bulbetski commented on internal/agent/client/client.go
> +		log.Fatalf("impossible to marshall metrics: %s", err)
Можно исправить вот таким образом. Это на случай, если мы хотим оставить Start блокирующей операцией.  Это нормально в приложениях, в которых основной задачей является запуск сервера. 
```
func (sm *ServerManager) Start(ctx context.Context) error {
	errChan := make(chan error, 1)

	go func() {
		errChan <- sm.server.ListenAndServe()
	}()

	select {
	case <-ctx.Done():
		return sm.server.Shutdown(context.Background())
	case err := <-errChan:
		return err
	}
}
```

Если хотим сделать неблокрирующий start и вернуть "ошибку", а не фаталиться, то можно, например, возвращать errChan и в самом конце main горутины ждать завершения работы Start. Но так в целом обычно не делают

```
	select {
	case err := <-errChan:
		if err != nil {
			log.Fatalf("Server failed: %v", err)
		}
	case <-ctx.Done():
		log.Println("Graceful shutdown complete")
	}
```

2024-11-17 17:11 UTC, bulbetski commented on internal/pkg/retry/retry.go
> +	for shouldRetry && curAttempt != attempts {
Не убрала, но ничо страшного

2024-11-17 17:12 UTC, bulbetski commented on internal/server/api/api.go
>  	newAPI.router = newAPI.newRouter()
и так, и так норм

2024-11-17 17:13 UTC, bulbetski commented on internal/server/service/service.go
>  		mval = strconv.FormatFloat(*metric.Value, 'f', -1, 64)
Вот тут забыли геттер

2024-11-17 17:14 UTC, bulbetski commented on internal/server/service/service.go
>  		mval = strconv.FormatInt(*metric.Delta, 10)
Геттер

2024-11-17 17:20 UTC, bulbetski commented on internal/server/storage/pg/pg.go
> +func NewStorage(dsn string) (*pgstorage, error) {
Преимущество в выполнении принципа единственной ответственности у функции. По сути у NewStorage создание подключения и пинг это сайд эффекты, которые как бы не имеют отношения к pgstorage с его репозиторными методами. Так же подключение из мэйна ты можешь передавать в разные зависимости. Скажем, у тебя будет несколько хранилищ через pg. В противном случае придется создавать несколько подключений, что действительно выглядит не очень хорошо.

Централизованная обработка ошибок подключений к внешним зависимостям это классический и наиболее популярный подход

2024-11-17 17:22 UTC, bulbetski commented on internal/server/storage/pg/pg.go
> +	return err
Технической нет. Конкретно в этой функции даже визуально особо профита нет. Но на будущее, если бы был какая-нибудь длинная имплементация, где фиг пойми что происходит, return err как-то говорит, будто тут явно какая-то ошибка происходит. А если ее там не происходит, об этом надо додуматься. 
Написание более чистого кода, где ты разделяешь err и nil, ты сама себе и другим облегчаешь жизнь

2024-11-17 17:24 UTC, bulbetski commented on internal/server/storage/pg/queries.go
> +package pg
sql еще только и делает, что мешается с go)))
заведено использовать либо raw sql внутри запросов, либо какой-нибудь squirrel для билда запросов. И всё это опять же внутри репозиторных методов. 

Нет, файлик отдельный не костыль. Прост неудобно. А ты понаблюдай, ок.

2024-11-17 17:25 UTC, bulbetski commented
Всё исправлено хорошо, код получился класс. Есть моменты, которые можно улучшить, но это придет с опытом

2024-11-18 07:53 UTC, ulixes-bloom commented on internal/pkg/retry/retry.go
> +	for shouldRetry && curAttempt != attempts {
блин, что за магия, я помню как смотрела этот кусок, и меняла return errorSlice на shouldRetry=false 
 спасибо, что заметил 🥲

2024-11-18 07:55 UTC, ulixes-bloom commented on internal/pkg/retry/retry.go
> +	for shouldRetry && curAttempt != attempts {
так.. это похоже outdated версия в гит ревью..
в коде исправлено
https://github.com/ulixes-bloom/ya-metrics/blob/iter13/internal/pkg/retry/retry.go#L50

2024-11-18 08:37 UTC, ulixes-bloom commented on internal/agent/client/client.go
> +		log.Fatalf("impossible to marshall metrics: %s", err)
спасибо, классные варианты. сделала по первому примеру
не додумалась так возвращать ошибку

2024-11-18 08:59 UTC, ulixes-bloom commented on internal/server/storage/pg/pg.go
> +func NewStorage(dsn string) (*pgstorage, error) {
интересно.. сохраню этот момент на подумать

2024-11-18 09:00 UTC, merged