Iter15
ulixes-bloom/ya-metrics pull request #15
Opened 2024-11-24 19:12 UTC by ulixes-bloom

2024-11-27 23:01 UTC, bulbetski requested changes
Код написан хорошо, без критический замечений. Единственное, что стоит сделать -- вынести воркер пул в отдельный пакет.

2024-11-27 23:01 UTC, bulbetski commented on internal/agent/client/client.go
> +			c.service.Poll(ctx)
Не обрабатываем ошибку

2024-11-27 23:01 UTC, bulbetski commented on internal/agent/client/client.go
Инициализируем storage внутри клиента, что нехорошо. Стоит вынести иницализацию в main и прокидывать внутрь клиента. Таким образом, к примеру, мы можем всего 1 раз иницаилизровать connection к бд, создать 1 репозиторий и переиспользовать его в разных сервисах

2024-11-27 23:01 UTC, bulbetski commented on internal/agent/client/client.go
> +		go c.worker(metricsToSendChan)
Воркер-пул — это универсальная сущность, которая может быть в дальнейшем полезна и в других частях приложения. Вынесение его в отдельный пакет улучшит повторное использование. 

простой набросок независимого воркер пула
```
type Task func()

type Pool struct {
	tasks   chan Task
	wg      sync.WaitGroup
	workers int
}
```

2024-11-27 23:01 UTC, bulbetski commented on internal/agent/client/worker.go
> +	client := &http.Client{}
Лучше сделать http клиент частью нашей client структуры. Так его легче конфигурировать и не нужно инициализировать каждый раз

2024-11-27 23:01 UTC, bulbetski commented on internal/agent/memory/memory.go
> +	mutex   *sync.RWMutex
Указатель на мьютекс не нужен, как и его явная инициализация

2024-11-27 23:01 UTC, bulbetski commented on internal/agent/service/service.go
> +	g, _ := errgroup.WithContext(ctx)
тут нам надо использовать контекст, который вернула errgroup.WithContext, чтобы корректно управлять жизненным циклом всех горутин в группе через этот контекст

2024-11-27 23:01 UTC, bulbetski commented on internal/agent/service/service.go
> +		s.pollRuntimeMetrics()
Внутри вызывается storage.Add, который возвращает ошибку, мы ее не обрабатываем не внутри функции, ни в месте вызова.

Вместо множественных вызовов storage.Add можно сделать какой-нибудь storage.AddMany или любое другое название на твое усмотрение. Потом 1 раз обработать ошибку, вернуть ее и обработать в месте вызова

2024-11-27 23:01 UTC, bulbetski commented on internal/agent/service/service.go
> +		return fmt.Errorf("failed to poll metrics: %w", err)
Вот тут будет не понятно, откуда вернулась ошибка. В каждой g.Go стоит вернуть ошибку по типу fmt.Errorf("pollSystemMetrics: %w", err)

2024-11-27 23:01 UTC, bulbetski commented on internal/agent/service/service.go
> +	s.storage.Add(metrics.NewGaugeMetric("CPUutilization1", float64(utilisation[0])))
1. Не обрабатываем ошибки
2. Можно объединить в 1 метод, чтобы не было страшно обрабатывать миллион ошибок

2024-11-27 23:01 UTC, bulbetski commented on internal/server/api/middleware/compress.go
> +		gw.w.Header().Add(headers.ContentEncoding, "gzip")
вместо Add можно использовать Set, чтобы избежать дублирования заголовков

2024-11-27 23:01 UTC, bulbetski commented on internal/server/api/middleware/hash.go
> +			err = r.Body.Close()
Достаточно просто defer r.body.Close() и потом проверить nil или не nil body

2024-11-27 23:01 UTC, bulbetski commented on internal/server/api/middleware/hash.go
> +				w.WriteHeader(wm.responseMemory.status)
Вместо того чтобы повторно вызывать WriteHeader после next.ServeHTTP, стоит настроить заголовки ответа (w.Header().Set(...)) и статус заранее, до передачи управления следующему обработчику (next.ServeHTTP). Это гарантирует, что WriteHeader вызывается ровно один раз.
Таким образом мы избежим нарушений спецификации HTTP:

В спецификации HTTP/1.1 (RFC 7230) указано, что вызов метода WriteHeader для http.ResponseWriter должен быть сделан только один раз для каждого HTTP-ответа. Если WriteHeader вызывается повторно, то поведение веб-сервера становится неопределенным

2024-11-28 00:17 UTC, bulbetski commented
Заметил, что нет части задания:

```
Добавьте в сервис новый хендлер DELETE /api/user/urls, который в теле запроса принимает список идентификаторов сокращённых URL для асинхронного удаления.

Успешно удалить URL может пользователь, его создавший. При запросе удалённого URL с помощью хендлера GET /{id} нужно вернуть статус 410 Gone.
```

2024-11-28 13:17 UTC, ulixes-bloom commented
> Заметил, что нет части задания:
> 
> Добавьте в сервис новый хендлер DELETE /api/user/urls, который в теле запроса принимает список идентификаторов сокращённых URL для асинхронного удаления.
> 
> Успешно удалить URL может пользователь, его создавший. При запросе удалённого URL с помощью хендлера GET /{id} нужно вернуть статус 410 Gone.

Похоже, это задание из трека url shortener, а у меня трек девопс про сбор метрик)

2024-11-28 19:53 UTC, ulixes-bloom commented on internal/server/api/middleware/hash.go
> +				w.WriteHeader(wm.responseMemory.status)
не очень понимаю, ка это исправить.. я не могу выставить хэш ответа до вызова следующего обработчика.. мне же нужно подписать данные которые я отправляю в ответе. а до вызова следующего обработчика этих данных еще нет

2024-11-28 19:56 UTC, ulixes-bloom commented on internal/agent/service/service.go
> +	g, _ := errgroup.WithContext(ctx)
да, не подумала.. поменяла так, чтобы ctx переопределялся

2024-11-28 20:16 UTC, ulixes-bloom commented on internal/server/api/middleware/hash.go
> +				w.WriteHeader(wm.responseMemory.status)
а..) ну как минимум можно WriteHeader не вызывать несколько раз 😅 убрала это

2024-12-03 02:56 UTC, bulbetski commented
Не код, а песня, молодец

2024-12-03 02:56 UTC, bulbetski approved these changes

2024-12-06 19:44 UTC, merged